FROM node:20-alpine3.18 as base

RUN apk --no-cache add curl
RUN curl -sL https://unpkg.com/@pnpm/self-installer | node

# All deps stage
FROM base as deps
ENV NPM_CONFIG_LOGLEVEL error
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --force

# Development stage
FROM base
ENV NODE_ENV development
WORKDIR /app
COPY --from=deps /app/node_modules /app/node_modules
COPY . .
EXPOSE 3000
CMD ["pnpm", "dev"]
